title: Databricks Notebook Archives
author: Masa Kitamura
# logo: 

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/ktmrmshk/dbbooks
  branch: master

html:
  use_issues_button: true
  use_repository_button: true

